POST http://localhost:8080/user
Authorisation: Bearer_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJwYXNzd29yZCI6InRlc3QifQ.TCLkDnac7iDcAT_brMVSFg6wJazeT0ZqTYanM4R7ZQo
Content-Type: application/json

{
  "name": "Test",
  "username": "test1",
  "password": "test",
  "roleList": [
  {
    "typeOfRole": "user"
  }
  ],
  "status": "active"
}

###

POST http://localhost:8080/number
Content-Type: application/json

{
  "id": 10,
  "triviaNumber": 22,
  "fact": "fact"
}
###
GET http://localhost:8080/user
Authorisation: Bearer_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJwYXNzd29yZCI6InRlc3QifQ.TCLkDnac7iDcAT_brMVSFg6wJazeT0ZqTYanM4R7ZQo