POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "Test",
  "username": "test2",
  "password": "test",
  "role": [
    {"typeOfRole": "USER"}
  ]
}

###

POST http://localhost:8080/number
Content-Type: application/json

{
  "id": 10,
  "triviaNumber": 22,
  "fact": "fact"
}
###